services:
  matchby:
    image: matchby
    build:
      context: .
      dockerfile: MatchBy/MatchBy/Dockerfile

  matchby.client:
    image: matchby.client
    build:
      context: .
      dockerfile: MatchBy/MatchBy.Client/Dockerfile

  matchby.postgres:
    image: postgres:17.2
    container_name: database.postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/database_data:/var/lib/postgressql/data
    ports:
      - 5432:5432
